[[events]]
name = "STRATOVIRT_SET_VOLUME_CB_FAILED"
event_type = "Fault"
args = "ERRCODE: i32"
enabled = true

[[events]]
name = "STRATOVIRT_GET_VOLUME_FAILED"
event_type = "Fault"
args = "ERRCODE: i32"
enabled = true

[[events]]
name = "STRATOVIRT_SET_VOLUME_FAILED"
event_type = "Fault"
args = "ERRCODE: i32"
enabled = true
