[package]
name = "oci_spec"
version = "0.1.0"
authors = ["Huawei StratoVirt Team"]
edition = "2021"
license = "Mulan PSL v2"
description = "Open Container Initiative (OCI) Specifications in Rust"

[dependencies]

[profile.dev]
panic = "unwind"

[profile.release]
lto = true
strip = true
opt-level = 'z'
codegen-units = 1
panic = "abort"