[[scopes]]
name = "address_space_read"
args = "addr: &dyn fmt::Debug, count: u64"
message = "Memory: flatview_read addr {:?}, count {}"
enabled = true

[[scopes]]
name = "address_space_write"
args = "addr: &dyn fmt::Debug, count: u64"
message = "Memory: flatview_write addr {:?}, count {}"
enabled = true

[[scopes]]
name = "address_space_read_direct"
args = "host_addr: u64, count: usize"
message = "Memory: address_space_read_direct host_addr {}, count {}"
enabled = true

[[scopes]]
name = "address_space_write_direct"
args = "host_addr: u64, count: usize"
message = "Memory: address_space_write_direct host_addr {}, count {}"
enabled = true

[[scopes]]
name = "address_update_topology"
args = ""
message = "Memory: update opology"
enabled = true

[[scopes]]
name = "pre_alloc"
args = "size: u64"
message = "Memory: pre_alloc ram size is {}"
enabled = true

[[scopes]]
name = "init_memory"
args = ""
message = "Memory: init memory"
enabled = true
