[[events]]
name = "pl031_read"
args = "addr: u64, value: u32"
message = "addr 0x{:04x} value 0x{:08x}"
enabled = true

[[events]]
name = "pl031_write"
args = "addr: u64, value: u32"
message = "addr 0x{:04x} value 0x{:08x}"
enabled = true

[[events]]
name = "pl031_inject_interrupt"
args = ""
message = ""
enabled = true

[[events]]
name = "rtc_read"
args = "addr: u8, value: u8"
message = "addr 0x{:02x} value 0x{:02x}"
enabled = true

[[events]]
name = "rtc_write"
args = "addr: u8, value: u8"
message = "addr 0x{:02x} value 0x{:02x}"
enabled = true

[[events]]
name = "rtc_inject_interrupt"
args = ""
message = ""
enabled = true

[[events]]
name = "pl011_read"
args = "addr: u64, value: u32"
message = "addr 0x{:08x} value 0x{:08x}"
enabled = true

[[events]]
name = "pl011_read_fifo"
args = "read_count: u32"
message = "FIFO read, read_count now {}"
enabled = true

[[events]]
name = "pl011_write"
args = "addr: u64, value: u32"
message = "addr 0x{:08x} value 0x{:08x}"
enabled = true

[[events]]
name = "pl011_interrupt"
args = "flag: u32"
message = "flag 0x{:08x}"
enabled = true

[[events]]
name = "pl011_baudrate_change"
args = "ibrd: u32, fbrd: u32"
message = "ibrd {}, fbrd {}"
enabled = true

[[events]]
name = "pl011_pause_rx"
args = ""
message = "rx paused"
enabled = true

[[events]]
name = "pl011_unpause_rx"
args = ""
message = "rx unpause"
enabled = true

[[events]]
name = "pl011_receive"
args = "value: u32, read_count: u32"
message = "new char 0x{:08x}, read_count now {}"
enabled = true

[[events]]
name = "pl011_receive_full"
args = ""
message = "FIFO now full, RXFF set"
enabled = true

[[events]]
name = "serial_read"
args = "addr: u64, value: u8"
message = "addr 0x{:08x} value 0x{:02x}"
enabled = true

[[events]]
name = "serial_write"
args = "addr: u64, value: u8"
message = "addr 0x{:08x} value 0x{:02x}"
enabled = true

[[events]]
name = "serial_update_iir"
args = "iir: u8"
message = "value 0x{:02x}"
enabled = true

[[events]]
name = "serial_receive"
args = "len: usize"
message = "data length {}"
enabled = true

[[events]]
name = "serial_pause_rx"
args = ""
message = "rx paused"
enabled = true

[[events]]
name = "serial_unpause_rx"
args = ""
message = "rx unpause"
enabled = true

[[events]]
name = "pflash_device_id"
args = "id: u32"
message = "read device ID: 0x{:04x}"
enabled = true

[[events]]
name = "pflash_device_info"
args = "offset: u64"
message = "read device information offset: 0x{:04x}"
enabled = true

[[events]]
name = "pflash_io_read"
args = "offset: u64, size: u32, value: u32, cmd: u8, wcycle: u32"
message = "offset: 0x{:04x}, size: {}, value: 0x{:04x}, cmd: 0x{:02x}, wcycle: {}"
enabled = true

[[events]]
name = "pflash_io_write"
args = "offset: u64, size: u8, value: u32, wcycle: u32"
message = "offset: 0x{:04x}, size: {}, value: 0x{:04x}, wcycle: {}"
enabled = true

[[events]]
name = "pflash_manufacturer_id"
args = "id: u32"
message = "read manufacturer ID: 0x{:04x}"
enabled = true

[[events]]
name = "pflash_mode_read_array"
args = ""
message = "read array mode"
enabled = true

[[events]]
name = "pflash_read_data"
args = "offset: u64, len: usize, value: &[u8]"
message = "data offset: 0x{:04x}, length: {}, value: 0x{:x?}"
enabled = true

[[events]]
name = "pflash_read_status"
args = "status: u32"
message = "status: 0x{:x}"
enabled = true

[[events]]
name = "pflash_read_unknown_state"
args = "cmd: u8"
message = "unknown command state: 0x{:02x}"
enabled = true

[[events]]
name = "pflash_write"
args = "str: String, cmd: u8"
message = "{}, cmd: 0x{:02x}"
enabled = true

[[events]]
name = "pflash_write_block"
args = "value: u32"
message = "block write: bytes: 0x{:x}"
enabled = true

[[events]]
name = "pflash_write_block_erase"
args = "offset: u64, len: u32"
message = "block erase offset: 0x{:04x}, bytes: 0x{:x}"
enabled = true

[[events]]
name = "pflash_write_data"
args = "offset: u64, size: usize, value: &[u8], counter: u32"
message = "data offset: 0x{:04x}, size: {}, value: 0x{:x?}, counter: 0x{:04x}"
enabled = true
