[[events]]
name = "usb_handle_control"
args = "device: &str, req: &dyn fmt::Debug"
message = "device {} handle control request {:?}."
enabled = true

[[events]]
name = "usb_camera_vs_control_request"
args = "cs: u8, vs_control: &dyn fmt::Debug"
message = "VideoStreamingControl {} {:?}."
enabled = true

[[events]]
name = "usb_camera_handle_control"
args = ""
message = "camera control handled by descriptor."
enabled = true

[[events]]
name = "usb_camera_handle_payload"
args = "frame_offset: usize, payload_offset: usize, data_size: u64, copied: usize"
message = "camera handle payload, frame_offset {} payloadoffset {} data_size {} copied {}."
enabled = true

[[events]]
name = "usb_storage_handle_control"
args = ""
message = "storage control handled by descriptor."
enabled = true

[[events]]
name = "usb_storage_handle_data"
args = "ep_number: u8, pid: u32, mode: &dyn fmt::Debug"
message = "endpoint {}, pid 0x{:X}, mode {:?}"
enabled = true

[[events]]
name = "usb_storage_handle_token_out"
args = "cbw: &dyn fmt::Debug"
message = "cbw {:?}"
enabled = true

[[events]]
name = "usb_storage_handle_token_in"
args = "csw: &dyn fmt::Debug"
message = "csw {:?}"
enabled = true

[[events]]
name = "usb_storage_handle_data_inout_packet"
args = "len: u32"
message = "iovec length {}"
enabled = true

[[events]]
name = "usb_storage_handle_scsi_request"
args = "csw: &dyn fmt::Debug"
message = "csw {:?}"
enabled = true
