[[events]]
name = "virtio_receive_request"
args = "device: String, behaviour: String"
message = "{}: Request received from guest {}, ready to start processing."
enabled = true

[[events]]
name = "virtqueue_send_interrupt"
args = "device: &str, queue: u64"
message = "{}: virtqueue 0x{:X?} processing complete, ready to send interrupt to guest."
enabled = true

[[events]]
name = "virtio_scsi_handle_cmd_req"
args = "target: u8, lun: u16, tag: u64, cmd: u8"
message = "target={}, lun={}, tag={}, cmd={}."
enabled = true

[[events]]
name = "virtio_scsi_handle_cmd_resp"
args = "target: u8, lun: u16, tag: u64, status: u8, response: u8"
message = "target={}, lun={}, tag={}, status={}, response={}."
enabled = true

[[events]]
name = "virtio_serial_output_data"
args = "iovec_size: u64, size: u64"
message = "iovec size {}, write size {}."
enabled = true

[[events]]
name = "virtio_serial_disconnected_port"
args = ""
message = "virtio-serial port is none or disconnected."
enabled = true

[[events]]
name = "virtio_rng_write_req_data"
args = "size: u32"
message = "size {}"
enabled = true

[[events]]
name = "virtio_blk_process_queue_suppress_notify"
args = "len: u16"
message = "len {}"
enabled = true

[[events]]
name = "virtio_blk_complete_request"
args = "status: u8"
message = "status {}"
enabled = true

[[events]]
name = "virtio_blk_complete_one_request"
args = "index: u16, len: u32"
message = "index {}, len {}"
enabled = true

[[events]]
name = "virtio_blk_execute"
args = "request_type: u32, len: usize, offset: usize"
message = "request type {}, iovecs len {}, offset {}"
enabled = true

[[events]]
name = "virtio_blk_handle_discard_write_zeroes_req"
args = "opcode: &dyn fmt::Debug, flags: u32, offset: usize, nbytes: u64"
message = "opcode {:?}, flags {}, offset {}, nbytes {}"
enabled = true

[[events]]
name = "virtio_blk_merge_req_queue"
args = "can_merge: bool, merged_reqs: u16, merged_iovs: usize, merged_bytes: u64"
message = "can_merge {}, merged_reqs {}, merged_iovs {}, merged_bytes {}"
enabled = true

[[events]]
name = "virtio_blk_read_config"
args = "offset: u64, data: &[u8]"
message = "offset {}, data {:?}"
enabled = true

[[events]]
name = "virtio_blk_write_config"
args = "offset: u64, data: &[u8]"
message = "offset {}, data {:?}"
enabled = true

[[events]]
name = "virtio_gpu_update_cursor"
args = "scanout: u32, x: u32, y: u32, res: u32, cmd: &str"
message = "scanout {}, x {}, y {}, resource {}, type {}."
enabled = true

[[events]]
name = "virtio_gpu_get_edid"
args = "scanout: u32"
message = "scanout {}."
enabled = true

[[events]]
name = "virtio_gpu_resource_create_2d"
args = "res: u32, fmt: u32, w: u32, h: u32"
message = "resource: {}, format {}, width {}, height {}."
enabled = true

[[events]]
name = "virtio_gpu_resource_unref"
args = "res: u32"
message = "resource: {}."
enabled = true

[[events]]
name = "virtio_gpu_xfer_toh_2d"
args = "res: u32"
message = "resource: {}."
enabled = true

[[events]]
name = "virtio_gpu_resource_flush"
args = "res: u32, w: u32, h: u32, x: u32, y: u32"
message = "resource: {}, width: {}, height: {}, x: {}, y: {}."
enabled = true

[[events]]
name = "virtio_gpu_set_scanout"
args = "res: u32, scanout: u32, w: u32, h: u32, x: u32, y: u32"
message = "resource: {}, scanout: {}, width: {}, height: {}, x: {}, y: {}."
enabled = true

[[events]]
name = "virtio_gpu_resource_attach_backing"
args = "res: u32"
message = "resource: {}."
enabled = true

[[events]]
name = "virtio_gpu_resource_detach_backing"
args = "res: u32"
message = "resource: {}."
enabled = true

[[events]]
name = "virtio_gpu_init_config_features"
args = "features: u64"
message = "features is {}."
enabled = true

[[events]]
name = "virtio_gpu_console_hw_update"
args = "con: usize, w: i32, h: i32"
message = "console {} receive hw update request, update size {} {}."
enabled = true
