[package]
name = "ozone"
version = "2.3.0"
authors = ["Huawei StratoVirt Team"]
edition = "2021"
description = "Provides protection for stratovirt"
license = "Mulan PSL v2"

[dependencies]
thiserror = "1.0"
anyhow = "1.0"
libc = "0.2"
nix = "0.26.2"

util = { path = "../util" }
